services:
    mysql:
        container_name: mysql
        image: mysql:latest
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - ${MYSQL_PORT}
        volumes:
            - './volumes/mysql/data:/var/lib/mysql'
            - './volumes/mysql/scripts:/docker-entrypoint-initdb.d'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: ${PMA_HOST}
            PMA_PORT: ${PMA_PORT}
        ports:
            - "${PORT_PHP_MYADMIN}:80"
        depends_on:
            - mysql
